#! /bin/bash

echo -e "\n\n###########################################"
echo -e "##      Starting Ubuntu Server API Service   ##"
echo -e "###########################################\n\n"

service start ubuntu-server-api