#! /bin/bash

echo '\n\n###########################################'
echo '##      Starting Ubuntu Server API Service   ##'
echo '###########################################\n\n'

service start ubuntu-server-api