#!/bin/bash
#       __  __     ______     __  __     __   __     ______   __  __
#      /\ \/\ \   /\  == \   /\ \/\ \   /\ "-.\ \   /\__  _\ /\ \/\ \
#      \ \ \_\ \  \ \  __<   \ \ \_\ \  \ \ \-.  \  \/_/\ \/ \ \ \_\ \
#       \ \_____\  \ \_____\  \ \_____\  \ \_\\"\_\    \ \_\  \ \_____\
#        \/_____/   \/_____/   \/_____/   \/_/ \/_/     \/_/   \/_____/
#
#          ______     ______     ______     __   __   ______     ______
#        /\  ___\   /\  ___\   /\  == \   /\ \ / /  /\  ___\   /\  == \
#        \ \___  \  \ \  __\   \ \  __<   \ \ \'/   \ \  __\   \ \  __<
#         \/\_____\  \ \_____\  \ \_\ \_\  \ \__|    \ \_____\  \ \_\ \_\
#          \/_____/   \/_____/   \/_/ /_/   \/_/      \/_____/   \/_/ /_/
#
#                                 ______     ______   __
#                                /\  __ \   /\  == \ /\ \
#                                \ \  __ \  \ \  _-/ \ \ \
#                                 \ \_\ \_\  \ \_\    \ \_\
#                                  \/_/\/_/   \/_/     \/_/

set -e

echo -e "\n"
echo -e "########################################################################"
echo -e "#                                                                      #"
echo -e "#  Installing requirements for building packages and adding apt repos  #"
echo -e "#                                                                      #"
echo -e "########################################################################"
echo -e "\n"

apt-get update
apt-get install -y build-essential python-software-properties python-pycurl git

echo -e "\n"
echo -e "########################################################################"
echo -e "#                                                                      #"
echo -e "#  Adding Richard Harvey's PPA for the latest Node.js packages         #"
echo -e "#                                                                      #"
echo -e "########################################################################"
echo -e "\n"

add-apt-repository -y ppa:richarvey/nodejs && apt-get update

echo -e "\n"
echo -e "########################################################################"
echo -e "#                                                                      #"
echo -e "#  Installing the latest versions of nodejs, npm and related dev libs  #"
echo -e "#                                                                      #"
echo -e "########################################################################"
echo -e "\n"

apt-get install -y nodejs nodejs-dev npm libsqlite3-dev libpam0g-dev

echo -e "\n"
echo -e "########################################################################"
echo -e "#                                                                      #"
echo -e "#  Installing the latest version of ubuntu-server-api                  #"
echo -e "#                                                                      #"
echo -e "########################################################################"
echo -e "\n"

npm install -g ubuntu-server-api
#apt-get install -y ubuntu-server-api