#!/bin/bash
set -e

echo -e "\n"
echo -e "########################################################################"
echo -e "#                                                                      #"
echo -e "#  Preparing to install Ubuntu Server API                              #"
echo -e "#                                                                      #"
echo -e "########################################################################"
echo -e "\n"

# Add usg-api User
/usr/sbin/adduser --system --disabled-password --no-create-home --group usgapi
echo 'usgapi ALL=(ALL:ALL) NOPASSWD: /usr/bin/node' >> /etc/sudoers