#! /bin/bash

echo -e '\n\n###########################################'
echo -e '## Preparing to install Ubuntu Server API ##'
echo -e '###########################################\n\n'

# Add usg-api User
/usr/sbin/adduser --system --disabled-login --disabled-password --no-create-home --group usg-api
echo 'usg-api ALL=(ALL:ALL) ALL' >> /etc/sudoers

# Update System
apt-get -y update

# Required for adding PPAs
apt-get install -y python-software-properties

# Adding Nodejs PPA
echo -e '\n\nAdding nodejs PPA repo'
add-apt-repository -y ppa:richarvey/nodejs

# Update System
apt-get -y update

echo -e '\n\n###########################################'
echo -e '##        Installing NodeJS & NPM          ##'
echo -e '###########################################\n\n'

apt-get -y install nodejs npm

echo -e '\n\n###########################################'
echo -e '##        Installing Ubuntu Server API       ##'
echo -e '###########################################\n\n'
#npm install -g ubuntu-server-api
npm install -g