#! /bin/bash

echo '\n\n###########################################'
echo '## Preparing to install Ubuntu Server API ##'
echo '###########################################\n\n'

# Add usg-api User
/usr/sbin/adduser --system --disabled-login --disabled-password --no-create-home --group usg-api
echo 'usg-api ALL=(ALL:ALL) ALL' >> /etc/sudoers

# Update System
apt-get -y update

# Required for adding PPAs
apt-get install -y python-software-properties

# Adding Nodejs PPA
echo '\n\nAdding nodejs PPA repo'
add-apt-repository -y ppa:richarvey/nodejs

# Update System
apt-get -y update

echo '\n\n###########################################'
echo '##        Installing NodeJS & NPM          ##'
echo '###########################################\n\n'

apt-get -y install nodejs npm

echo '\n\n###########################################'
echo '##        Installing Ubuntu Server API       ##'
echo '###########################################\n\n'
#npm install -g ubuntu-server-api
npm install -g